version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  graphdb:
    restart: always
    image: ontotext/graphdb:10.3.3
    ports:
      - '7200:7200'
    container_name: graphdb
    environment:
      - GDB_HEAP_SIZE=24G
    volumes:
      - ./graphdb-home:/opt/graphdb/home
      - ./graphdb-init:/repository.init
  backend:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-}
    volumes:
      - ../tei1:/tei
      - ../backend-logs:/logs
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 9000:9000
    volumes:
      - ./frontend/nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/build/resources/main/static:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    restart: unless-stopped
volumes:
  data: