version: '3.3'

services:
  dhpp-mhdbdb:
    image: dhpp-mhdbdb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
#    network_mode: host
#networks:
#  target_default:
#    external: true
