
# This contains only properties different from application.properties
# this is for connectiong to the dhinfra server over OpenVPN (as user) 
target.host=http://imarealbackendtest01.dhinfra.plus.ac.at:3030/dhPLUS/sparql
target.host.engine=fuseki
target.username=admin
target.password=password

## actuators
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=none
## OpenApi
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# TODO see https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints.sanitization
# should be when-authorized with maybe a role as well
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always

### Logging
# we could set this to debug but there will be far too much clutter
logging.level.root=info
# override application.properties 
logging.file.name=./logs/mhdbdb-dhinfraImareal.log

# TEI
app.dev.frontend.teiFolder=D:/devel/imaReal/MHDBDB/data/TEI/tei1
app.dev.frontend.teiRenderedFolder=D:/devel/imaReal/MHDBDB/data/TEI/tei1/rendered
app.dev.frontend.additionalXmlPath=D:/devel/imaReal/MHDBDB/data/TEI/tei1/additionalXml.xml
app.dev.frontend.teiPdfolder=D:/devel/imaReal/MHDBDB/data/TEI/tei1/pdf
