prefix bf: <http://id.loc.gov/ontologies/bibframe/>
prefix bflc: <http://id.loc.gov/ontologies/bflc/>
prefix cc: <http://creativecommons.org/ns#>
prefix constants: <https://dh.plus.ac.at/constants/>
prefix crm: <http://www.cidoc-crm.org/cidoc-crm/>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dct: <http://purl.org/dc/terms/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix decomp: <http://www.w3.org/ns/lemon/decomp#>
prefix dhplusi: <https://dh.plus.ac.at/instance/>
prefix dhpluso: <https://dh.plus.ac.at/ontology#>
prefix dhplusoValidation: <https://dh.plus.ac.at/dhplusoValidation/>
prefix dhplusv: <https://dh.plus.ac.at/vocabulary/>
prefix dnb: <https://d-nb.info/>
prefix dnbt: <https://d-nb.info/standards/elementset/dnb#>
prefix ecrm: <http://erlangen-crm.org/200717/>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix gnd: <https://d-nb.info/gnd/>
prefix gndo: <https://d-nb.info/standards/elementset/gnd#>
prefix lexinfo: <http://www.lexinfo.net/ontology/3.0/lexinfo#>
prefix lime: <http://www.w3.org/ns/lemon/lime#>
prefix luc: <http://www.ontotext.com/connectors/lucene#>
prefix luc-index: <http://www.ontotext.com/connectors/lucene/instance#>
prefix mhdbdbi: <https://dh.plus.ac.at/mhdbdb/instance/>
prefix mhdbdbo: <https://dh.plus.ac.at/mhdbdb/ontology#>
prefix mhdbdbxml: <https://mhdbdbd.plus.ac.at/xml-ontology#>
prefix oa: <http://www.w3.org/ns/oa#>
prefix ogcsf: <http://www.opengis.net/ont/sf#>
prefix ontolex: <http://www.w3.org/ns/lemon/ontolex#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix parameter: <https://dh.plus.ac.at/parameter-ontology#>
prefix parameteri: <https://dh.plus.ac.at/parameter/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix sf: <http://www.opengis.net/ont/sf#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix szd: <https://gams.uni-graz.at/o,szd.ontology#>
prefix tei: <http://www.tei-c.org/ns/1.0#>
prefix time: <http://www.w3.org/2006/time#>
prefix tmp: <https://dh.plus.ac.at/tmp/>
prefix vann: <http://purl.org/vocab/vann/>
prefix wd: <http://www.wikidata.org/entity/>
prefix wdrs: <http://www.w3.org/2007/05/powder-s#>
prefix wds: <http://www.wikidata.org/entity/statement/>
prefix wdt: <http://www.wikidata.org/prop/direct/>
prefix wdtn: <http://www.wikidata.org/prop/direct-normalized/>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select * where {?s ?p ?o .} 